-- update vermittlungslisten to dynamical show and hide
INSERT  INTO `opsz_vermittlungslisten_references` (`referencetag`,`allowed_values`) VALUES ('_angenommen_therapie','["_HIDE_"]');
INSERT  INTO `opsz_vermittlungslisten_references` (`referencetag`,`depends_on_key`,`depends_on_value`,`allowed_values`) VALUES ('_angenommen_therapie','therapieantrag[5];local','Angenommen','["_SHOW_"]');
INSERT  INTO `opsz_vermittlungslisten_references` (`referencetag`,`depends_on_key`,`depends_on_value`,`allowed_values`) VALUES ('_angenommen_therapie','therapieantrag[5];local','Teilweise angenommen','["_SHOW_"]');
UPDATE `opsz_vermittlungslisten_permissions`SET `keymachine`= 'therapieantrag',`keyreadable`= 'Therapieantrag: Verfahrensstand + zuständige Behörde + ges. Grundlage + gestellt am + Antwort am + Entscheidung + Widerspruch + Bewilligungsbeginn + Bewilligungsende + Folgeantrag zu stellen bis',`realid`= '13.000',`typelist`= 'TEXT',`edittype`= 'LIST + LIST + TEXT + DATE + DATE + LIST + LIST + DATE + DATE + DATE; MULTIPLE',`referencetag`= '_verfahrensstand + _behoerde + _none_ + _none_ + _none_ + _entscheidung + _widerspruch_therapie + _angenommen_therapie + _angenommen_therapie + _angenommen_therapie' WHERE `keymachine`= 'therapieantrag';
INSERT  INTO `opsz_vermittlungslisten_references` (`referencetag`,`allowed_values`) VALUES ('_angenommen_dolmetscherinnen','["_HIDE_"]');
INSERT  INTO `opsz_vermittlungslisten_references` (`referencetag`,`depends_on_key`,`depends_on_value`,`allowed_values`) VALUES ('_angenommen_dolmetscherinnen','dolmetscherinnenantrag[5];local','Angenommen','["_SHOW_"]');
INSERT  INTO `opsz_vermittlungslisten_references` (`referencetag`,`depends_on_key`,`depends_on_value`,`allowed_values`) VALUES ('_angenommen_dolmetscherinnen','dolmetscherinnenantrag[5];local','Teilweise angenommen','["_SHOW_"]');
UPDATE `opsz_vermittlungslisten_permissions`SET `keymachine`= 'dolmetscherinnenantrag',`keyreadable`= 'Dolmetscherinnenantrag: Verfahrensstand + zuständige Behörde + ges. Grundlage + gestellt am + Antwort am + Entscheidung + Widerspruch + Bewilligungsbeginn + Bewilligungsende + Folgeantrag zu stellen bis',`realid`= '13.000',`typelist`= 'TEXT',`edittype`= 'LIST + LIST + TEXT + DATE + DATE + LIST + LIST + DATE + DATE + DATE; MULTIPLE',`referencetag`= '_verfahrensstand + _behoerde + _none_ + _none_ + _none_ + _entscheidung + _widerspruch_dolmetscherinnen + _angenommen_dolmetscherinnen + _angenommen_dolmetscherinnen + _angenommen_dolmetscherinnen' WHERE `keymachine`= 'dolmetscherinnenantrag';
INSERT  INTO `opsz_vermittlungslisten_references` (`referencetag`,`allowed_values`) VALUES ('_angenommen_fahrtkosten','["_HIDE_"]');
INSERT  INTO `opsz_vermittlungslisten_references` (`referencetag`,`depends_on_key`,`depends_on_value`,`allowed_values`) VALUES ('_angenommen_fahrtkosten','fahrtkostenantrag[6];local','Angenommen','["_SHOW_"]');
INSERT  INTO `opsz_vermittlungslisten_references` (`referencetag`,`depends_on_key`,`depends_on_value`,`allowed_values`) VALUES ('_angenommen_fahrtkosten','fahrtkostenantrag[6];local','Teilweise angenommen','["_SHOW_"]');
UPDATE `opsz_vermittlungslisten_permissions`SET `keymachine`= 'fahrtkostenantrag',`keyreadable`= 'Fahrtkostenantrag: Verfahrensstand + zuständige Behörde + ges. Grundlage + Zweck + gestellt am + Antwort am + Entscheidung + Widerspruch + Bewilligungsbeginn + Bewilligungsende + Folgeantrag zu stellen bis',`realid`= '15.000',`typelist`= 'TEXT',`edittype`= 'LIST + LIST + TEXT + TEXT + DATE + DATE + LIST + LIST + DATE + DATE + DATE; MULTIPLE',`referencetag`= '_verfahrensstand + _behoerde + _none_ + _none_ + _none_ + _none_ + _entscheidung + _widerspruch_fahrtkosten + _angenommen_fahrtkosten + _angenommen_fahrtkosten + _angenommen_fahrtkosten' WHERE `keymachine`= 'fahrtkostenantrag';
