-- enlarge field referencetag
ALTER TABLE opsz_vermittlungslisten_permissions MODIFY referencetag VARCHAR(511);

-- Dolmetscheranträge erstellen
UPDATE `os_functions` SET `functionconfig`= '{"terminbrief":{"default":{"namereadable":"Terminbrief erstellen","description":"erstellt einen Terminbrief aus der Vorlage","src":"Terminbriefvorlage.odt","filename":"$opsz_aufnahme__name - $opsz_aufnahme__vorname.odt","vars":{"NAME":"$opsz_aufnahme__name","VORNAME":"$opsz_aufnahme__vorname","ADRESSE":"$opsz_aufnahme__adresse","DATUM":"$ENV(date)","ANREDE":"%%if ( $opsz_aufnahme__geschlecht == 'weiblich' ) { 'Liebe Frau' } %%else { 'Lieber Herr'} %%endif","TYP_WEIBLICH":"%%if ( $opsz_vermittlungslisten__vermitteltzu[1][this] == 'PsychiaterInnen' ) { 'Psychiaterin' } %%endif %%if ( $opsz_vermittlungslisten__vermitteltzu[1][this] == 'TherapeutInnen' ) { 'Therapeutin' } %%endif","TYP_MAENNLICH":"%%if ( $opsz_vermittlungslisten__vermitteltzu[1][this] == 'PsychiaterInnen' ) { 'Psychiater' } %%endif %%if ( $opsz_vermittlungslisten__vermitteltzu[1][this] == 'TherapeutInnen' ) { 'Therapeut' } %%endif","TERMINDATUM":"$opsz_vermittlungslisten__vermitteltzu[4][this]","PTNAME":"$opsz_vermittlungslisten__vermitteltzu[2][this]","PTADRESSE":"$opsz_vermittlungslisten__vermitteltzu[3][this]"}}},"dolmiantrag":{"default":{"namereadable":"Dolmetschkostenantrag erstellen","description":"erstellt einen Antrag auf Übernahme von Dolmetschkosten aus der Vorlage","src":"%%if ( $opsz_aufnahme__gesundheitsversorgung == 'keine' ) { 'DolmetschantragJobcenter.odt' } %%endif %%if ( $opsz_aufnahme__gesundheitsversorgung == 'Sozialamt' ) { 'DolmetschantragSozialamtEingeschraenkt.odt' } %%endif %%if ( $opsz_aufnahme__gesundheitsversorgung == 'Krankenkasse über Sozialamt' ) { 'DolmetschantragSozialamtKrankenkassekarte.odt' } %%endif","filename":"Dolmetschantrag - $opsz_aufnahme__gesundheitsversorgung - $opsz_aufnahme__name - $opsz_aufnahme__vorname.odt","vars":{"BVORNAME":"$PROFILE(~)[vorname]","BNAME":"$PROFILE(~)[name]","BTELEFON":"$PROFILE(~)[telefon]","BEMAIL":"$PROFILE(~)[email]","KVORNAME":"$opsz_aufnahme__vorname","KNAME":"$opsz_aufnahme__name","KGEBDATUM":"$opsz_aufnahme__geburtsdatum","KADRESSE":"$opsz_aufnahme__adresse","KSYMPTOMATIK":"$opsz_aufnahme__symptomatik","KANREDE":"%%if ( $opsz_aufnahme__geschlecht == 'weiblich' ) { 'Frau' } %%else { 'Herr'} %%endif","PNAME":"$opsz_vermittlungslisten__vermitteltzu[2][this]","CDATUM":"$ENV(date)"}}}}',`functionflags`= '[{"ONTABLES":{"terminbrief":["opsz_vermittlungslisten"],"dolmiantrag":["opsz_vermittlungslisten"]}}]' WHERE `functionmachine`= 'createFromTemplate';
INSERT  INTO `opsz_vermittlungslisten_references` (`referencetag`,`allowed_values`) VALUES ('_dolmiantrag_erstellen','["createFromTemplate(dolmiantrag)"]');
UPDATE `opsz_vermittlungslisten_permissions` SET `keyreadable`= 'Dolmetscherinnenantrag: Verfahrensstand + zuständige Behörde + ges. Grundlage + gestellt am + Antwort am + Entscheidung + Widerspruch + Bewilligungsbeginn + Bewilligungsende + Folgeantrag zu stellen bis + Widerspruch eingelegt am + Antrag erstellen',`edittype`= 'LIST + LIST + TEXT + DATE + DATE + LIST + LIST + DATE + DATE + DATE + DATE + FUNCTION; MULTIPLE',`referencetag`= '_verfahrensstand + _behoerde + _none_ + _none_ + _none_ + _entscheidung + _widerspruch_dolmetscherinnen + _angenommen_dolmetscherinnen + _angenommen_dolmetscherinnen + _angenommen_dolmetscherinnen + _eingelegt_widerspruch_dolmetscherinnen + _dolmiantrag_erstellen' WHERE `keymachine`= 'dolmetscherinnenantrag';

-- DONT FORGET to copy vendor specific templates to vendor/templates/
