-- openStatAdmin-log started 01.28.2021 14:07:35
ALTER TABLE `opsz_vermittlungslisten` DROP COLUMN `listentyp`;
DELETE FROM `opsz_vermittlungslisten_permissions` WHERE id = '3';
UPDATE `opsz_vermittlungslisten_permissions`SET `id`= '4',`keymachine`= 'auflisteseit',`keyreadable`= 'Aufnahme in die Vermittlung am',`realid`= '4.000',`typelist`= 'DATE',`edittype`= 'DATE',`role_0`= '0',`role_1`= '0',`role_7`= '0',`role_8`= '0',`role_31`= '0' WHERE id = 4;
ALTER TABLE `opsz_vermittlungslisten` ADD COLUMN `vermittlungsauftrag` VARCHAR(40) DEFAULT NULL;
INSERT  INTO `opsz_vermittlungslisten_permissions` (`keymachine`,`keyreadable`,`realid`,`typelist`,`edittype`,`referencetag`) VALUES ('vermittlungsauftrag','Vermittlungsauftrag','6','VARCHAR(40)','LIST','_vermittlungsauftrag');
ALTER TABLE `opsz_vermittlungslisten` ADD COLUMN `stand` VARCHAR(20) DEFAULT NULL;
INSERT  INTO `opsz_vermittlungslisten_permissions` (`keymachine`,`keyreadable`,`realid`,`typelist`,`edittype`,`referencetag`) VALUES ('stand','Stand der Vermittlung','8','VARCHAR(20)','LIST','_stand');
ALTER TABLE `opsz_vermittlungslisten` ADD COLUMN `uebernommenvon` TEXT DEFAULT NULL;
INSERT  INTO `opsz_vermittlungslisten_permissions` (`keymachine`,`keyreadable`,`realid`,`typelist`,`edittype`) VALUES ('uebernommenvon','übernommen von','9','TEXT','EXTENSIBLE LIST');
ALTER TABLE `opsz_vermittlungslisten` ADD COLUMN `anmerkung` TEXT DEFAULT NULL;
INSERT  INTO `opsz_vermittlungslisten_permissions` (`keymachine`,`keyreadable`,`realid`,`typelist`,`edittype`) VALUES ('anmerkung','Anmerkung','10','TEXT','FREE');
ALTER TABLE `opsz_vermittlungslisten` ADD COLUMN `vermitteltzu` TEXT DEFAULT NULL;
INSERT  INTO `opsz_vermittlungslisten_permissions` (`keymachine`,`keyreadable`,`realid`,`typelist`,`edittype`,`referencetag`) VALUES ('vermitteltzu','Vermittelt zu: Datum der Vermittlung + Bereich + Name, Vorname + Adresse + Datum des ersten Termins','11','TEXT','DATE + LIST + TEXT + FREE + DATE; MULTIPLE','_none_ + _bereich');
ALTER TABLE `opsz_vermittlungslisten` ADD COLUMN `angefragtbei` TEXT DEFAULT NULL;
INSERT  INTO `opsz_vermittlungslisten_permissions` (`keymachine`,`keyreadable`,`realid`,`typelist`,`edittype`) VALUES ('angefragtbei','angefragte TherapeutInnen / ÄrztInnen: Datum + Name, Vorname + Ort + Ergebnis','12','TEXT','DATE + TEXT + FREE + FREE; MULTIPLE');
ALTER TABLE `opsz_vermittlungslisten` ADD COLUMN `therapieantrag` TEXT DEFAULT NULL;
INSERT  INTO `opsz_vermittlungslisten_permissions` (`keymachine`,`keyreadable`,`realid`,`typelist`,`edittype`,`referencetag`) VALUES ('therapieantrag','Therapieantrag: Verfahrensstand + zuständige Behörde + gestellt am + Antwort am + Entscheidung + Widerspruch','13','TEXT','LIST + LIST + DATE + DATE + LIST + LIST; MULTIPLE','_verfahrensstand + _behoerde + _none_ + _none_ + _entscheidung + _binary');
UPDATE `opsz_vermittlungslisten_permissions`SET `id`= '13',`keymachine`= 'therapieantrag',`keyreadable`= 'Therapieantrag: Verfahrensstand + zuständige Behörde + gestellt am + Antwort am + Entscheidung + Widerspruch',`realid`= '13.000',`typelist`= 'TEXT',`edittype`= 'LIST + LIST + DATE + DATE + LIST + LIST',`referencetag`= '_verfahrensstand + _behoerde + _none_ + _none_ + _entscheidung + _widerspruch',`role_0`= '0',`role_1`= '0',`role_7`= '0',`role_8`= '0',`role_31`= '0' WHERE id = 13;
ALTER TABLE `opsz_vermittlungslisten` ADD COLUMN `dolmetscherinnenantrag` TEXT DEFAULT NULL;
INSERT  INTO `opsz_vermittlungslisten_permissions` (`keymachine`,`keyreadable`,`realid`,`typelist`,`edittype`,`referencetag`) VALUES ('dolmetscherinnenantrag','Dolmetscherinnenantrag: Verfahrensstand + zuständige Behörde + gestellt am + Antwort am + Entscheidung + Widerspruch','13.000','TEXT','LIST + LIST + DATE + DATE + LIST + LIST; MULTIPLE','_verfahrensstand + _behoerde + _none_ + _none_ + _entscheidung + _widerspruch');
UPDATE `opsz_vermittlungslisten_permissions`SET `id`= '14',`keymachine`= 'dolmetscherinnenantrag',`keyreadable`= 'Dolmetscherinnenantrag: Verfahrensstand + zuständige Behörde + gestellt am + Antwort am + Entscheidung + Widerspruch',`realid`= '14.000',`typelist`= 'TEXT',`edittype`= 'LIST + LIST + DATE + DATE + LIST + LIST',`referencetag`= '_verfahrensstand + _behoerde + _none_ + _none_ + _entscheidung + _widerspruch',`role_0`= '0',`role_1`= '0',`role_7`= '0',`role_8`= '0',`role_31`= '0' WHERE id = 14;
ALTER TABLE `opsz_vermittlungslisten` ADD COLUMN `fahrtkostenantrag` TEXT DEFAULT NULL;
INSERT  INTO `opsz_vermittlungslisten_permissions` (`keymachine`,`keyreadable`,`realid`,`typelist`,`edittype`,`referencetag`) VALUES ('fahrtkostenantrag','Fahrtkostenantrag: Verfahrensstand + zuständige Behörde + gestellt am + Antwort am + Entscheidung + Widerspruch','15.000','TEXT','LIST + LIST + DATE + DATE + LIST + LIST; MULTIPLE','_verfahrensstand + _behoerde + _none_ + _none_ + _entscheidung + _widerspruch');
DELETE FROM `opsz_vermittlungslisten_references`; 
INSERT INTO `opsz_vermittlungslisten_references` VALUES (1,'_none_',NULL,NULL,NULL),(2,'_vermittlungsauftrag',NULL,NULL,'[\"Psychotherapievermittlung\",\"PsychiaterInvermittlung\",\"Beratungsstelle\",\"Sonstiges\"]'),(3,'_stand',NULL,NULL,'[\"*nicht anwendbar\",\"anderweitig\",\"erfolgreich\",\"im Prozess\"]'),(4,'_bereich',NULL,NULL,'[\"TherapeutInnen\",\"PsychiaterInnen\",\"Beratungsstelle\",\"Sonstiges\"]'),(5,'_verfahrensstand',NULL,NULL,'[\"Erstantrag\",\"Zweitantrag\",\"Widerspruch\"]'),(6,'_behoerde',NULL,NULL,'[\"Sozialamt\",\"Jobcenter\",\"Jugendhilfe\",\"Krankenkasse\"]'),(7,'_entscheidung',NULL,NULL,'[\"*Keine Entscheidung\",\"Angenommen\",\"Ablehnung\"]'),(8,'_widerspruch',NULL,NULL,'[\"*nicht anwendbar\",\"nein\",\"ja\"]'),(9,'_widerspruch_fahrtkosten','fahrtkostenantrag[4];local','Ablehnung','[\"nein\",\"ja\"]'),(10,'_widerspruch_fahrtkosten',NULL,NULL,'[\"*nicht anwendbar\"]'),(11,'_widerspruch_dolmetscherinnen',NULL,NULL,'[\"*nicht anwendbar\"]'),(12,'_widerspruch_therapie',NULL,NULL,'[\"*nicht anwendbar\"]'),(13,'_widerspruch_dolmetscherinnen','dolmetscherinnenantrag[4];local','Ablehnung','[\"nein\",\"ja\"]'),(14,'_widerspruch_therapie','therapieantrag[4];local','Ablehnung','[\"nein\",\"ja\"]');
UPDATE `os_tables`SET `iconname`= 'clipboard-list',`tablemachine`= 'opsz_vermittlungslisten',`tablereadable`= 'Vermittlungsliste',`displayforeign`= '["opsz_aufnahme__verantwortlich","opsz_aufnahme__name","opsz_aufnahme__vorname","opsz_aufnahme__adresse","opsz_aufnahme__muttersprache","opsz_aufnahme__genderaspekte","opsz_aufnahme__gesundheitsversorgung","opsz_aufnahme__lebensunterhalt","opsz_aufnahme__swes"]' WHERE tablemachine = 'opsz_vermittlungslisten';
-- openStatAdmin-log finished 01.28.2021 15:23:36
