-- openStatAdmin-log started 01.28.2021 14:07:35
-- allow longer entries for comppund fields
alter table opsz_vermittlungslisten_permissions modify column referencetag VARCHAR(255);
alter table opsz_vermittlungslisten_permissions modify column edittype VARCHAR(255);
--
ALTER TABLE `opsz_vermittlungslisten` DROP COLUMN `listentyp`;
DELETE FROM `opsz_vermittlungslisten_permissions` WHERE id = '3';
UPDATE `opsz_vermittlungslisten_permissions`SET `id`= '4',`keymachine`= 'auflisteseit',`keyreadable`= 'Aufnahme in die Vermittlung am',`realid`= '4.000',`typelist`= 'DATE',`edittype`= 'DATE' WHERE id = 4;
ALTER TABLE `opsz_vermittlungslisten` ADD COLUMN `vermittlungsauftrag` VARCHAR(40) DEFAULT NULL;
INSERT  INTO `opsz_vermittlungslisten_permissions` (`keymachine`,`keyreadable`,`realid`,`typelist`,`edittype`,`referencetag`) SELECT 'vermittlungsauftrag','Vermittlungsauftrag','6','VARCHAR(40)','LIST','_vermittlungsauftrag' FROM DUAL WHERE (SELECT count(*) FROM information_schema.COLUMNS WHERE TABLE_NAME = 'opsz_vermittlungslisten' AND COLUMN_NAME = 'vermittlungsauftrag') > 0 AND (SELECT count(keymachine) FROM `opsz_vermittlungslisten_permissions` where keymachine = 'vermittlungsauftrag') = 0;
ALTER TABLE `opsz_vermittlungslisten` ADD COLUMN `stand` VARCHAR(20) DEFAULT NULL;
INSERT  INTO `opsz_vermittlungslisten_permissions` (`keymachine`,`keyreadable`,`realid`,`typelist`,`edittype`,`referencetag`) SELECT 'stand','Stand der Vermittlung','8','VARCHAR(20)','LIST','_stand' FROM DUAL WHERE (SELECT count(*) FROM information_schema.COLUMNS WHERE TABLE_NAME = 'opsz_vermittlungslisten' AND COLUMN_NAME = 'stand') > 0 AND (SELECT count(keymachine) FROM `opsz_vermittlungslisten_permissions` where keymachine = 'stand') = 0;
ALTER TABLE `opsz_vermittlungslisten` ADD COLUMN `uebernommenvon` TEXT DEFAULT NULL;
INSERT  INTO `opsz_vermittlungslisten_permissions` (`keymachine`,`keyreadable`,`realid`,`typelist`,`edittype`) SELECT 'uebernommenvon','übernommen von','9','TEXT','EXTENSIBLE LIST' FROM DUAL WHERE (SELECT count(*) FROM information_schema.COLUMNS WHERE TABLE_NAME = 'opsz_vermittlungslisten' AND COLUMN_NAME = 'uebernommenvon') > 0 AND (SELECT count(keymachine) FROM `opsz_vermittlungslisten_permissions` where keymachine = 'uebernommenvon') = 0;
ALTER TABLE `opsz_vermittlungslisten` ADD COLUMN `anmerkung` TEXT DEFAULT NULL;
INSERT  INTO `opsz_vermittlungslisten_permissions` (`keymachine`,`keyreadable`,`realid`,`typelist`,`edittype`) SELECT 'anmerkung','Anmerkung','10','TEXT','FREE' FROM DUAL WHERE (SELECT count(*) FROM information_schema.COLUMNS WHERE TABLE_NAME = 'opsz_vermittlungslisten' AND COLUMN_NAME = 'anmerkung') > 0 AND (SELECT count(keymachine) FROM `opsz_vermittlungslisten_permissions` where keymachine = 'anmerkung') = 0;
ALTER TABLE `opsz_vermittlungslisten` ADD COLUMN `vermitteltzu` TEXT DEFAULT NULL;
INSERT  INTO `opsz_vermittlungslisten_permissions` (`keymachine`,`keyreadable`,`realid`,`typelist`,`edittype`,`referencetag`) SELECT 'vermitteltzu','Vermittelt zu: Datum der Vermittlung + Bereich + Name, Vorname + Adresse + Datum des ersten Termins','11','TEXT','DATE + LIST + TEXT + FREE + DATE; MULTIPLE','_none_ + _bereich' FROM DUAL WHERE (SELECT count(*) FROM information_schema.COLUMNS WHERE TABLE_NAME = 'opsz_vermittlungslisten' AND COLUMN_NAME = 'vermitteltzu') > 0 AND (SELECT count(keymachine) FROM `opsz_vermittlungslisten_permissions` where keymachine = 'vermitteltzu') = 0;
ALTER TABLE `opsz_vermittlungslisten` ADD COLUMN `angefragtbei` TEXT DEFAULT NULL;
INSERT  INTO `opsz_vermittlungslisten_permissions` (`keymachine`,`keyreadable`,`realid`,`typelist`,`edittype`) SELECT 'angefragtbei','angefragte TherapeutInnen / ÄrztInnen: Datum + Name, Vorname + Ort + Ergebnis','12','TEXT','DATE + TEXT + FREE + FREE; MULTIPLE' FROM DUAL WHERE (SELECT count(*) FROM information_schema.COLUMNS WHERE TABLE_NAME = 'opsz_vermittlungslisten' AND COLUMN_NAME = 'angefragtbei') > 0 AND (SELECT count(keymachine) FROM `opsz_vermittlungslisten_permissions` where keymachine = 'angefragtbei') = 0;
ALTER TABLE `opsz_vermittlungslisten` ADD COLUMN `therapieantrag` TEXT DEFAULT NULL;
INSERT  INTO `opsz_vermittlungslisten_permissions` (`keymachine`,`keyreadable`,`realid`,`typelist`,`edittype`,`referencetag`) SELECT 'therapieantrag','Therapieantrag: Verfahrensstand + zuständige Behörde + gestellt am + Antwort am + Entscheidung + Widerspruch','13','TEXT','LIST + LIST + DATE + DATE + LIST + LIST; MULTIPLE','_verfahrensstand + _behoerde + _none_ + _none_ + _entscheidung + _widerspruch_therapie' FROM DUAL WHERE (SELECT count(*) FROM information_schema.COLUMNS WHERE TABLE_NAME = 'opsz_vermittlungslisten' AND COLUMN_NAME = 'therapieantrag') > 0 AND (SELECT count(keymachine) FROM `opsz_vermittlungslisten_permissions` where keymachine = 'therapieantrag') = 0;
ALTER TABLE `opsz_vermittlungslisten` ADD COLUMN `dolmetscherinnenantrag` TEXT DEFAULT NULL;
INSERT  INTO `opsz_vermittlungslisten_permissions` (`keymachine`,`keyreadable`,`realid`,`typelist`,`edittype`,`referencetag`) SELECT 'dolmetscherinnenantrag','Dolmetscherinnenantrag: Verfahrensstand + zuständige Behörde + gestellt am + Antwort am + Entscheidung + Widerspruch','13.000','TEXT','LIST + LIST + DATE + DATE + LIST + LIST; MULTIPLE','_verfahrensstand + _behoerde + _none_ + _none_ + _entscheidung + _widerspruch_dolmetscherinnen' FROM DUAL WHERE (SELECT count(*) FROM information_schema.COLUMNS WHERE TABLE_NAME = 'opsz_vermittlungslisten' AND COLUMN_NAME = 'dolmetscherinnenantrag') > 0 AND (SELECT count(keymachine) FROM `opsz_vermittlungslisten_permissions` where keymachine = 'dolmetscherinnenantrag') = 0;
ALTER TABLE `opsz_vermittlungslisten` ADD COLUMN `fahrtkostenantrag` TEXT DEFAULT NULL;
INSERT  INTO `opsz_vermittlungslisten_permissions` (`keymachine`,`keyreadable`,`realid`,`typelist`,`edittype`,`referencetag`) SELECT 'fahrtkostenantrag','Fahrtkostenantrag: Verfahrensstand + zuständige Behörde + gestellt am + Antwort am + Entscheidung + Widerspruch','15.000','TEXT','LIST + LIST + DATE + DATE + LIST + LIST; MULTIPLE','_verfahrensstand + _behoerde + _none_ + _none_ + _entscheidung + _widerspruch_fahrtkosten' FROM DUAL WHERE (SELECT count(*) FROM information_schema.COLUMNS WHERE TABLE_NAME = 'opsz_vermittlungslisten' AND COLUMN_NAME = 'fahrtkostenantrag') > 0 AND (SELECT count(keymachine) FROM `opsz_vermittlungslisten_permissions` where keymachine = 'fahrtkostenantrag') = 0;
DELETE FROM `opsz_vermittlungslisten_references`;
INSERT INTO `opsz_vermittlungslisten_references` VALUES (1,'_none_',NULL,NULL,NULL);
INSERT INTO `opsz_vermittlungslisten_references` VALUES (2,'_vermittlungsauftrag',NULL,NULL,'["Psychotherapievermittlung","PsychiaterInvermittlung","Beratungsstelle","Sonstiges"]');
INSERT INTO `opsz_vermittlungslisten_references` VALUES (3,'_stand',NULL,NULL,'["*nicht anwendbar","anderweitig","erfolgreich","im Prozess"]');
INSERT INTO `opsz_vermittlungslisten_references` VALUES (4,'_bereich',NULL,NULL,'["*nicht anwendbar","TherapeutInnen","PsychiaterInnen","Beratungsstelle","Sonstiges"]');
INSERT INTO `opsz_vermittlungslisten_references` VALUES (5,'_verfahrensstand',NULL,NULL,'["*nicht anwendbar","Erstantrag","Zweitantrag","Widerspruch"]');
INSERT INTO `opsz_vermittlungslisten_references` VALUES (6,'_behoerde',NULL,NULL,'["*nicht anwendbar","Sozialamt","Jobcenter","Jugendhilfe","Krankenkasse"]');
INSERT INTO `opsz_vermittlungslisten_references` VALUES (7,'_entscheidung',NULL,NULL,'["*Keine Entscheidung","Entscheidung ausstehend","Teilweise angenommen","Angenommen","Ablehnung"]');
INSERT INTO `opsz_vermittlungslisten_references` VALUES (8,'_widerspruch',NULL,NULL,'["*nicht anwendbar","nein","ja"]');
INSERT INTO `opsz_vermittlungslisten_references` VALUES (9,'_widerspruch_fahrtkosten','fahrtkostenantrag[4];local','Ablehnung','["nein","ja"]');
INSERT INTO `opsz_vermittlungslisten_references` VALUES (10,'_widerspruch_fahrtkosten','fahrtkostenantrag[4];local','Teilweise angenommen','["nein","ja"]');
INSERT INTO `opsz_vermittlungslisten_references` VALUES (11,'_widerspruch_fahrtkosten',NULL,NULL,'["*nicht anwendbar"]');
INSERT INTO `opsz_vermittlungslisten_references` VALUES (12,'_widerspruch_dolmetscherinnen',NULL,NULL,'["*nicht anwendbar"]');
INSERT INTO `opsz_vermittlungslisten_references` VALUES (13,'_widerspruch_therapie',NULL,NULL,'["*nicht anwendbar"]');
INSERT INTO `opsz_vermittlungslisten_references` VALUES (14,'_widerspruch_dolmetscherinnen','dolmetscherinnenantrag[4];local','Ablehnung','["nein","ja"]');
INSERT INTO `opsz_vermittlungslisten_references` VALUES (15,'_widerspruch_dolmetscherinnen','dolmetscherinnenantrag[4];local','Teilweise angenommen','["nein","ja"]');
INSERT INTO `opsz_vermittlungslisten_references` VALUES (16,'_widerspruch_therapie','therapieantrag[4];local','Ablehnung','["nein","ja"]');
INSERT INTO `opsz_vermittlungslisten_references` VALUES (17,'_widerspruch_therapie','therapieantrag[4];local','Teilweise angenommen','["nein","ja"]');
UPDATE `os_tables`SET `iconname`= 'clipboard-list',`tablemachine`= 'opsz_vermittlungslisten',`tablereadable`= 'Vermittlungsliste',`displayforeign`= '["opsz_aufnahme__verantwortlich","opsz_aufnahme__name","opsz_aufnahme__vorname","opsz_aufnahme__adresse","opsz_aufnahme__muttersprache","opsz_aufnahme__genderaspekte","opsz_aufnahme__gesundheitsversorgung","opsz_aufnahme__lebensunterhalt","opsz_aufnahme__swes"]' WHERE tablemachine = 'opsz_vermittlungslisten';
-- openStatAdmin-log finished 01.28.2021 15:23:36
