-- Korrektur für (keine -> Krankenkasse) Dolmetscheranträge erstellen
-- und Ergänzung von vars
UPDATE `os_functions` SET `functionconfig`= '{"terminbrief":{"default":{"namereadable":"Terminbrief erstellen","description":"erstellt einen Terminbrief aus der Vorlage","src":"Terminbriefvorlage.odt","filename":"$opsz_aufnahme__name - $opsz_aufnahme__vorname.odt","vars":{"NAME":"$opsz_aufnahme__name","VORNAME":"$opsz_aufnahme__vorname","ADRESSE":"$opsz_aufnahme__adresse","DATUM":"$ENV(date)","ANREDE":"%%if ( $opsz_aufnahme__geschlecht == 'weiblich' ) { 'Liebe Frau' } %%else { 'Lieber Herr'} %%endif","TYP_WEIBLICH":"%%if ( $opsz_vermittlungslisten__vermitteltzu[1][this] == 'PsychiaterInnen' ) { 'Psychiaterin' } %%endif %%if ( $opsz_vermittlungslisten__vermitteltzu[1][this] == 'TherapeutInnen' ) { 'Therapeutin' } %%endif","TYP_MAENNLICH":"%%if ( $opsz_vermittlungslisten__vermitteltzu[1][this] == 'PsychiaterInnen' ) { 'Psychiater' } %%endif %%if ( $opsz_vermittlungslisten__vermitteltzu[1][this] == 'TherapeutInnen' ) { 'Therapeut' } %%endif","TERMINDATUM":"$opsz_vermittlungslisten__vermitteltzu[4][this]","PTNAME":"$opsz_vermittlungslisten__vermitteltzu[2][this]","PTADRESSE":"$opsz_vermittlungslisten__vermitteltzu[3][this]"}}},"dolmiantrag":{"default":{"namereadable":"Dolmetschkostenantrag erstellen","description":"erstellt einen Antrag auf Übernahme von Dolmetschkosten aus der Vorlage","src":"%%if ( $opsz_aufnahme__gesundheitsversorgung == 'Krankenkasse' ) { 'DolmetschantragJobcenter.odt' } %%endif %%if ( $opsz_aufnahme__gesundheitsversorgung == 'Sozialamt' ) { 'DolmetschantragSozialamtEingeschraenkt.odt' } %%endif %%if ( $opsz_aufnahme__gesundheitsversorgung == 'Krankenkasse über Sozialamt' ) { 'DolmetschantragSozialamtKrankenkassekarte.odt' }%%endif","filename":"Dolmetschantrag - $opsz_aufnahme__gesundheitsversorgung - $opsz_aufnahme__name - $opsz_aufnahme__vorname.odt","vars":{"ANAME":"$PUBLIC(~opsz_vermittlungslisten__dolmetscherinnenantrag[1][this])[NAME]","AADRESSE":"$PUBLIC(~opsz_vermittlungslisten__dolmetscherinnenantrag[1][this])[ADRESSE]","APLZ":"$PUBLIC(~opsz_vermittlungslisten__dolmetscherinnenantrag[1][this])[PLZ]","AORT":"$PUBLIC(~opsz_vermittlungslisten__dolmetscherinnenantrag[1][this])[ORT]","BVORNAME":"$PROFILE(~)[vorname]","BNAME":"$PROFILE(~)[name]","BFUNKTION":"$PROFILE(~)[funktion]","BTELEFON":"$PROFILE(~)[telefon]","BEMAIL":"$PROFILE(~)[email]","KVORNAME":"$opsz_aufnahme__vorname","KNAME":"$opsz_aufnahme__name","KGEBDATUM":"$opsz_aufnahme__geburtsdatum","KADRESSE":"$opsz_aufnahme__adresse","KSYMPTOMATIK":"$opsz_aufnahme__symptomatik[all]","KANREDE":"%%if ( $opsz_aufnahme__geschlecht == 'weiblich' ) { 'Frau' } %%else { 'Herr'} %%endif","PNAME":"$opsz_vermittlungslisten__vermitteltzu[2][this]","CDATUM":"$ENV(date)"}}}}',`functionflags`= '[{"ONTABLES":{"terminbrief":["opsz_vermittlungslisten"],"dolmiantrag":["opsz_vermittlungslisten"]}}]' WHERE `functionmachine`= 'createFromTemplate';
-- Vorlagen für Öffentliche Infos
INSERT INTO `os_public` (tags,data) SELECT 'Jobcenter','{"NAME":"","ADRESSE":"","PLZ":"","ORT":"","TELEFON":"","EMAIL":""}' FROM DUAL WHERE  (SELECT count() FROM `os_public` where  = '{"NAME":"","ADRESSE":"","PLZ":"","ORT":"","TELEFON":"","EMAIL":""}') = 0;
INSERT INTO `os_public` (tags,data) SELECT 'Sozialamt','{"NAME":"","ADRESSE":"","PLZ":"","ORT":"","TELEFON":"","EMAIL":""}' FROM DUAL WHERE  (SELECT count() FROM `os_public` where  = '{"NAME":"","ADRESSE":"","PLZ":"","ORT":"","TELEFON":"","EMAIL":""}') = 0;
INSERT INTO `os_public` (tags,data) SELECT 'Jugendhilfe','{"NAME":"","ADRESSE":"","PLZ":"","ORT":"","TELEFON":"","EMAIL":""}' FROM DUAL WHERE  (SELECT count() FROM `os_public` where  = '{"NAME":"","ADRESSE":"","PLZ":"","ORT":"","TELEFON":"","EMAIL":""}') = 0;
INSERT INTO `os_public` (tags,data) SELECT 'Krankenkasse','{"NAME":"","ADRESSE":"","PLZ":"","ORT":"","TELEFON":"","EMAIL":""}' FROM DUAL WHERE  (SELECT count() FROM `os_public` where  = '{"NAME":"","ADRESSE":"","PLZ":"","ORT":"","TELEFON":"","EMAIL":""}') = 0;
-- ergänze offentliche Infos in Behördenreferenz
UPDATE `opsz_vermittlungslisten_references` SET `allowed_values` = '["Sozialamt","Jobcenter","Jugendhilfe","Krankenkasse","_PUBLIC:Sozialamt:_","_PUBLIC:Jobcenter:_","_PUBLIC:Jugendhilfe:_","_PUBLIC:Krankenkasse:_"]' WHERE `referencetag` = '_behoerde';
-- DONT FORGET to copy vendor specific templates to vendor/templates/
