-- this makes opszdiffv1.14.0-1.0.sql obsolete
-- update function configs
UPDATE `os_functions` SET `functionconfig`= '{"terminbrief":{"default":{"namereadable":"Terminbrief erstellen","description":"erstellt einen Terminbrief aus der Vorlage","src":"Terminbriefvorlage.odt","filename":"$opsz_aufnahme__name - $opsz_aufnahme__vorname.odt","vars":{"NAME":"$opsz_aufnahme__name","VORNAME":"$opsz_aufnahme__vorname","ADRESSE":"$opsz_aufnahme__adresse","DATUM":"$ENV(date)","ANREDE":"%%if ( $opsz_aufnahme__geschlecht == \'weiblich\' ) { \'Liebe Frau\' } %%else { \'Lieber Herr\'} %%endif","TYP_WEIBLICH":"%%if ( $opsz_vermittlungslisten__vermitteltzu[1][this] == \'PsychiaterInnen\' ) { \'Psychiaterin\' } %%endif %%if ( $opsz_vermittlungslisten__vermitteltzu[1][this] == \'TherapeutInnen\' ) { \'Therapeutin\' } %%endif","TYP_MAENNLICH":"%%if ( $opsz_vermittlungslisten__vermitteltzu[1][this] == \'PsychiaterInnen\' ) { \'Psychiater\' } %%endif %%if ( $opsz_vermittlungslisten__vermitteltzu[1][this] == \'TherapeutInnen\' ) { \'Therapeut\' } %%endif","TERMINDATUM":"$opsz_vermittlungslisten__vermitteltzu[4][this]","PTNAME":"$opsz_vermittlungslisten__vermitteltzu[2][this]","PTADRESSE":"$opsz_vermittlungslisten__vermitteltzu[3][this]"}}}}',`functionflags`= '[{"ONTABLES":{"terminbrief":["opsz_vermittlungslisten"]}}]' WHERE `functionmachine`= 'createFromTemplate';
UPDATE `os_functions` SET `functionflags` = '[{"ONTABLES":{"vermittlungsersttermin":["opsz_vermittlungslisten"]}}]', `functionconfig`= '{"vermittlungsersttermin":{"default":{"namereadable":"Erster Termin einer Vermittlung","description":"Erzeugt den ersten Termin einer erfolgreichen Vermittlung","srcTable":"opsz_vermittlungslisten","trgt":[{"tablemachine":"opsz_termine","keys":{"typ":"Vermittlung","beginn":"$opsz_vermittlungslisten__vermitteltzu[4][this]","ende":"$opsz_vermittlungslisten__vermitteltzu[4][this]","bei":"$opsz_vermittlungslisten__vermitteltzu[2][this]","beiadresse":"$opsz_vermittlungslisten__vermitteltzu[3][this]","titel":"Ersttermin","id_opsz_aufnahme":"$opsz_aufnahme__id_opsz_aufnahme"}}]}}}' WHERE `functionmachine`= 'createSubsequentEntry';
-- add "erstelle Terminbrief" and "erstelle Ersttermin" zu Vermittlungslisten "vermittelt zu"
UPDATE `opsz_vermittlungslisten_permissions` SET `keyreadable`= 'Vermittelt zu: Datum der Vermittlung + Bereich + Name, Vorname + Adresse + Datum des ersten Termins + erstelle Ersttermin + erstelle Terminbrief',`edittype`= 'DATE + LIST + TEXT + FREE + DATETIME + FUNCTION + FUNCTION; MULTIPLE',`referencetag`= '_none_ + _bereich + _none_ + _none_ + _none_ + _erstelleErstTermin + _erstelleBrief' WHERE `keymachine`= 'vermitteltzu';
INSERT  INTO `opsz_vermittlungslisten_references` (`referencetag`,`allowed_values`) VALUES ('_erstelleErstTermin','["createSubsequentEntry(vermittlungsersttermin)"]');
INSERT  INTO `opsz_vermittlungslisten_references` (`referencetag`,`allowed_values`) VALUES ('_erstelleBrief','["_SHOW_","createFromTemplate(terminbrief)"]');
-- remove former separate fields for those functions
ALTER TABLE `opsz_vermittlungslisten` DROP COLUMN `erstelleBrief`;
DELETE FROM `opsz_vermittlungslisten_permissions` WHERE `keymachine`= 'erstelleBrief';
ALTER TABLE `opsz_vermittlungslisten` DROP COLUMN `erstelleErstTermin`;
DELETE FROM `opsz_vermittlungslisten_permissions` WHERE `keymachine`= 'erstelleErstTermin';
