-- update vermittlungslisten to dynamical show and hide
DELETE FROM `opsz_vermittlungslisten_references` WHERE `referencetag`= '_angenommen_fahrtkosten';
DELETE FROM `opsz_vermittlungslisten_references` WHERE `referencetag`= '_angenommen_dolmetscherinnen';
DELETE FROM `opsz_vermittlungslisten_references` WHERE `referencetag`= '_angenommen_therapie';

INSERT  INTO `opsz_vermittlungslisten_references` (`referencetag`,`allowed_values`) VALUES ('_angenommen_therapie','["_HIDE_"]');
INSERT  INTO `opsz_vermittlungslisten_references` (`referencetag`,`depends_on_key`,`depends_on_value`,`allowed_values`) VALUES ('_angenommen_therapie','therapieantrag[5];local','Angenommen','["_SHOW_"]');
INSERT  INTO `opsz_vermittlungslisten_references` (`referencetag`,`depends_on_key`,`depends_on_value`,`allowed_values`) VALUES ('_angenommen_therapie','therapieantrag[5];local','Teilweise angenommen','["_SHOW_"]');
UPDATE `opsz_vermittlungslisten_permissions`SET `keymachine`= 'therapieantrag',`keyreadable`= 'Therapieantrag: Verfahrensstand + zuständige Behörde + ges. Grundlage + gestellt am + Antwort am + Entscheidung + Widerspruch + Bewilligungsbeginn + Bewilligungsende + Folgeantrag zu stellen bis',`realid`= '13.000',`typelist`= 'TEXT',`edittype`= 'LIST + LIST + TEXT + DATE + DATE + LIST + LIST + DATE + DATE + DATE; MULTIPLE',`referencetag`= '_verfahrensstand + _behoerde + _none_ + _none_ + _none_ + _entscheidung + _widerspruch_therapie + _angenommen_therapie + _angenommen_therapie + _angenommen_therapie' WHERE `keymachine`= 'therapieantrag';

INSERT  INTO `opsz_vermittlungslisten_references` (`referencetag`,`allowed_values`) VALUES ('_angenommen_dolmetscherinnen','["_HIDE_"]');
INSERT  INTO `opsz_vermittlungslisten_references` (`referencetag`,`depends_on_key`,`depends_on_value`,`allowed_values`) VALUES ('_angenommen_dolmetscherinnen','dolmetscherinnenantrag[5];local','Angenommen','["_SHOW_"]');
INSERT  INTO `opsz_vermittlungslisten_references` (`referencetag`,`depends_on_key`,`depends_on_value`,`allowed_values`) VALUES ('_angenommen_dolmetscherinnen','dolmetscherinnenantrag[5];local','Teilweise angenommen','["_SHOW_"]');
UPDATE `opsz_vermittlungslisten_permissions`SET `keymachine`= 'dolmetscherinnenantrag',`keyreadable`= 'Dolmetscherinnenantrag: Verfahrensstand + zuständige Behörde + ges. Grundlage + gestellt am + Antwort am + Entscheidung + Widerspruch + Bewilligungsbeginn + Bewilligungsende + Folgeantrag zu stellen bis',`realid`= '13.000',`typelist`= 'TEXT',`edittype`= 'LIST + LIST + TEXT + DATE + DATE + LIST + LIST + DATE + DATE + DATE; MULTIPLE',`referencetag`= '_verfahrensstand + _behoerde + _none_ + _none_ + _none_ + _entscheidung + _widerspruch_dolmetscherinnen + _angenommen_dolmetscherinnen + _angenommen_dolmetscherinnen + _angenommen_dolmetscherinnen' WHERE `keymachine`= 'dolmetscherinnenantrag';

INSERT  INTO `opsz_vermittlungslisten_references` (`referencetag`,`allowed_values`) VALUES ('_angenommen_fahrtkosten','["_HIDE_"]');
INSERT  INTO `opsz_vermittlungslisten_references` (`referencetag`,`depends_on_key`,`depends_on_value`,`allowed_values`) VALUES ('_angenommen_fahrtkosten','fahrtkostenantrag[6];local','Angenommen','["_SHOW_"]');
INSERT  INTO `opsz_vermittlungslisten_references` (`referencetag`,`depends_on_key`,`depends_on_value`,`allowed_values`) VALUES ('_angenommen_fahrtkosten','fahrtkostenantrag[6];local','Teilweise angenommen','["_SHOW_"]');
UPDATE `opsz_vermittlungslisten_permissions`SET `keymachine`= 'fahrtkostenantrag',`keyreadable`= 'Fahrtkostenantrag: Verfahrensstand + zuständige Behörde + ges. Grundlage + Zweck + gestellt am + Antwort am + Entscheidung + Widerspruch + Bewilligungsbeginn + Bewilligungsende + Folgeantrag zu stellen bis',`realid`= '15.000',`typelist`= 'TEXT',`edittype`= 'LIST + LIST + TEXT + TEXT + DATE + DATE + LIST + LIST + DATE + DATE + DATE; MULTIPLE',`referencetag`= '_verfahrensstand + _behoerde + _none_ + _none_ + _none_ + _none_ + _entscheidung + _widerspruch_fahrtkosten + _angenommen_fahrtkosten + _angenommen_fahrtkosten + _angenommen_fahrtkosten' WHERE `keymachine`= 'fahrtkostenantrag';

DELETE FROM `opsz_vermittlungslisten_references` WHERE `referencetag`= '_widerspruch_fahrtkosten';
DELETE FROM `opsz_vermittlungslisten_references` WHERE `referencetag`= '_widerspruch_dolmetscherinnen';
DELETE FROM `opsz_vermittlungslisten_references` WHERE `referencetag`= '_widerspruch_therapie';
INSERT INTO `opsz_vermittlungslisten_references` (`referencetag`,`depends_on_key`,`depends_on_value`,`allowed_values`) VALUES ('_widerspruch_fahrtkosten','fahrtkostenantrag[6];local','Ablehnung','[\"_SHOW_\",\"nein\",\"ja\"]'),('_widerspruch_fahrtkosten','fahrtkostenantrag[6];local','Teilweise angenommen','[\"_SHOW_\",\"nein\",\"ja\"]'),('_widerspruch_fahrtkosten',NULL,NULL,'[\"_HIDE_\",\"*nicht anwendbar\"]'),('_widerspruch_dolmetscherinnen',NULL,NULL,'[\"_HIDE_\",\"*nicht anwendbar\"]'),('_widerspruch_therapie',NULL,NULL,'[\"_HIDE_\",\"*nicht anwendbar\"]'),('_widerspruch_dolmetscherinnen','dolmetscherinnenantrag[5];local','Ablehnung','[\"_SHOW_\",\"nein\",\"ja\"]'),('_widerspruch_dolmetscherinnen','dolmetscherinnenantrag[5];local','Teilweise angenommen','[\"_SHOW_\",\"nein\",\"ja\"]'),('_widerspruch_therapie','therapieantrag[5];local','Ablehnung','[\"_SHOW_\",\"nein\",\"ja\"]'),('_widerspruch_therapie','therapieantrag[5];local','Teilweise angenommen','[\"_SHOW_\",\"nein\",\"ja\"]');

DELETE FROM `opsz_vermittlungslisten_references` WHERE `referencetag`= '_show';
INSERT  INTO `opsz_vermittlungslisten_references` (`referencetag`,`depends_on_key`,`depends_on_value`,`allowed_values`) VALUES ('_show','angefragtbei[4];local','ja','["_SHOW_"]');
INSERT  INTO `opsz_vermittlungslisten_references` (`referencetag`,`allowed_values`) VALUES ('_show','["_HIDE_"]');
UPDATE `opsz_vermittlungslisten_permissions`SET `keymachine`= 'angefragtbei',`keyreadable`= 'angefragte TherapeutInnen / ÄrztInnen: Datum + Name, Vorname + Ort + Ergebnis + Warteliste + nachfragen ab',`realid`= '12.000',`typelist`= 'TEXT',`edittype`= 'DATE + TEXT + FREE + FREE + LIST + DATE; MULTIPLE',`referencetag`= '_none_ + _none_ + _none_ + _none_ + _yesno + _show' WHERE `keymachine`= 'angefragtbei';
