-- insert new field ueberleitungnach in refuKey table and add option "PSZ Hannover"
ALTER TABLE opsz_refukey ADD COLUMN `ueberleitungnach` VARCHAR(8);
INSERT INTO opsz_refukey_permissions (keymachine,keyreadable,realid,typelist,edittype,referencetag) SELECT 'ueberleitungnach','Überleitung innerhalb refuKey nach',5.1,'VARCHAR(40)','LIST','_evalueberleitung' FROM DUAL WHERE (SELECT count(*) FROM information_schema.COLUMNS WHERE TABLE_NAME = 'opsz_refukey' AND COLUMN_NAME = 'ueberleitungnach') > 0 AND (SELECT count(keymachine) FROM `opsz_refukey_permissions` where keymachine = 'ueberleitungnach') = 0;
UPDATE opsz_refukey_references SET allowed_values='["*nein","PSZ Lüneburg","PSZ Braunschweig","PSZ Göttingen","PSZ Oldenburg ","PSZ Osnabrück","PSZ Hannover","AWO Psychiatriezentrum Königslutter","Asklepios Fachklinikum Göttingen" ,"Niels-Stensen-Kliniken Bramsche","Karl-Jaspers Klinik Wehnen"]' WHERE referencetag = '_evalueberleitung';
UPDATE opsz_refukey_permissions SET keyreadable = "Überleitung innerhalb refuKey von" where keymachine = 'ueberleitung';

-- different name of refukey table in hannover and in development
ALTER TABLE opsz_evaluation ADD COLUMN `ueberleitungnach` VARCHAR(8);
INSERT INTO opsz_evaluation_permissions (keymachine,keyreadable,realid,typelist,edittype,referencetag) SELECT 'ueberleitungnach','Überleitung innerhalb refuKey nach',5.1,'VARCHAR(40)','LIST','_evalueberleitung' FROM DUAL WHERE (SELECT count(*) FROM information_schema.COLUMNS WHERE TABLE_NAME = 'opsz_evaluation' AND COLUMN_NAME = 'ueberleitungnach') > 0 AND (SELECT count(keymachine) FROM `opsz_evaluation_permissions` where keymachine = 'ueberleitungnach') = 0;
UPDATE opsz_evaluation_references SET allowed_values='["*nein","PSZ Lüneburg","PSZ Braunschweig","PSZ Göttingen","PSZ Oldenburg ","PSZ Osnabrück","PSZ Hannover","AWO Psychiatriezentrum Königslutter","Asklepios Fachklinikum Göttingen" ,"Niels-Stensen-Kliniken Bramsche","Karl-Jaspers Klinik Wehnen"]' WHERE referencetag = '_evalueberleitung';
UPDATE opsz_evaluation_permissions SET keyreadable = "Überleitung innerhalb refuKey von" where keymachine = 'ueberleitung';

-- set config for new trafficLight
UPDATE os_functions SET functionconfig = '{"criteria":[{"name":"zu lange auf Liste Stellungnahme","sql":"SELECT DATEDIFF(CURRENT_DATE(),stellungnahmeseit) from opsz_aufnahme WHERE DATEDIFF(CURRENT_DATE(),stellungnahmeseit) > 41","relation":">","benchmark":"41","urgency":1,"table":"opsz_aufnahme","display":"Tage"},{"name":"zu lange auf Liste Stellungnahme","sql":"SELECT DATEDIFF(CURRENT_DATE(),stellungnahmeseit) from opsz_aufnahme WHERE DATEDIFF(CURRENT_DATE(),stellungnahmeseit) > 89","relation":">","benchmark":"89","urgency":3,"table":"opsz_aufnahme"},{"name":"zu lange auf Vermittlungslisten","sql":"SELECT DATEDIFF(CURRENT_DATE(),auflisteseit) from opsz_vermittlungslisten WHERE DATEDIFF(CURRENT_DATE(),auflisteseit) > 41","relation":">","benchmark":"41","urgency":1,"table":"opsz_aufnahme","display":"Tage"},{"name":"zu lange auf Vermittlungslisten","sql":"SELECT DATEDIFF(CURRENT_DATE(),auflisteseit) from opsz_vermittlungslisten WHERE DATEDIFF(CURRENT_DATE(),auflisteseit) > 89","relation":">","benchmark":"89","urgency":3,"table":"opsz_aufnahme"},{"name":"zu viele Termine in 6 Monaten und nur OS","notimplies":[{"sql":"SELECT count(id_opsz_aufnahme) from opsz_termine WHERE beginn < CURRENT_DATE() AND beginn >= DATE_ADD(CURRENT_DATE(), INTERVAL -6 MONTH)","relation":">=","benchmark":"5","display":""},{"sql":"SELECT count(id_opsz_aufnahme) from opsz_termine WHERE beginn < CURRENT_DATE() AND beginn >= DATE_ADD(CURRENT_DATE(), INTERVAL -6 MONTH) AND typ != \'OS\'","relation":">","benchmark":"0"}],"urgency":1,"table":"opsz_aufnahme"},{"name":"zu viele Termine in 6 Monaten und nur OS","notimplies":[{"sql":"SELECT count(id_opsz_aufnahme) from opsz_termine WHERE beginn < CURRENT_DATE() AND beginn >= DATE_ADD(CURRENT_DATE(), INTERVAL -6 MONTH)","relation":">=","benchmark":"10"},{"sql":"SELECT count(id_opsz_aufnahme) from opsz_termine WHERE beginn < CURRENT_DATE() AND beginn >= DATE_ADD(CURRENT_DATE(), INTERVAL -6 MONTH) AND typ != \'OS\'","relation":">","benchmark":"0"}],"urgency":2,"table":"opsz_aufnahme"},{"name":"zu viele Termine in 6 Monaten und nur OS","notimplies":[{"sql":"SELECT count(id_opsz_aufnahme) from opsz_termine WHERE beginn < CURRENT_DATE() AND beginn >= DATE_ADD(CURRENT_DATE(), INTERVAL -6 MONTH)","relation":">=","benchmark":"20"},{"sql":"SELECT count(id_opsz_aufnahme) from opsz_termine WHERE beginn < CURRENT_DATE() AND beginn >= DATE_ADD(CURRENT_DATE(), INTERVAL -6 MONTH) AND typ != \'OS\'","relation":">","benchmark":"0"}],"urgency":3,"table":"opsz_aufnahme"}],"identifiers":{"opsz_aufnahme":["name","vorname"]}}' WHERE functionmachine = 'trafficLight';

-- register function exportRefuKey
INSERT INTO os_functions (iconname,functionmachine,functionreadable,functionscope,functionclasses,allowed_roles,functiontarget) SELECT 'file-medical-alt','exportRefuKey','refuKey-Export','RESULTDETAILS','details import','[0]','_popup_' FROM DUAL WHERE (SELECT count(functionmachine) FROM `os_functions` where functionmachine = 'exportRefuKey') = 0;
